- hosts: flask_api_backend
  vars_files:
    - "./vars/default_variables.yml"
    - "./vars/app_config.yml"
  remote_user: "{{ default_remote_user }}"
  # become: true

  tasks:
    - name: Update all packages
      become: true
      apt:
        update_cache: yes
        name: "*"
        state: latest

    - name: Install dependencies
      become: true
      apt:
        pkg:
          - git
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - htop

    - name: Add Docker GPG apt Key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      become: true
      apt:
        update_cache: true
        pkg:
          - docker-ce
          - docker-ce-cli 
          - containerd.io
          - docker-compose-plugin
          - docker-compose

    - name: Add user to docker group
      become: true
      user:
        name: "{{ default_remote_user }}"
        groups: docker
        append: yes

    - name: Upload private SSH key
      copy:
        src: "/home/parallels/.ssh/id_ed25519"
        dest: "~/.ssh/id_ed25519"
        mode: "0600"
        force: yes

    - name: Upload public SSH key
      copy:
        src: "/home/parallels/.ssh/id_ed25519.pub"
        dest: "~/.ssh/id_ed25519.pub"
        mode: "0600"
        force: yes    

    - name: Clone app repository
      git:
        repo: "{{ flask_api_repo }}"
        dest: "{{ flask_remote_path }}"
        key_file: "~/.ssh/github"
        clone: yes 
        accept_newhostkey: yes

    - name: Copy env variables
      template:
        src: "templates/env.j2"
        dest: "{{ flask_remote_path }}/.env"
        force: yes
        mode: "755"

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: "{{ flask_remote_path }}"
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: "{{ flask_remote_path }}"
        state: present